// Generated by <a href="http://scalaxb.org/">scalaxb</a>.
package org.birchavenue.eway

trait ManagedCreditCardPaymentSoap {
  def createCustomer(value: org.birchavenue.eway.CreateCustomer, eWAYHeader: org.birchavenue.eway.EWAYHeader): Either[scalaxb.Fault[Any], org.birchavenue.eway.CreateCustomerResponse]
  def updateCustomer(value: org.birchavenue.eway.UpdateCustomer, eWAYHeader: org.birchavenue.eway.EWAYHeader): Either[scalaxb.Fault[Any], Boolean]
  def queryCustomer(value: org.birchavenue.eway.QueryCustomer, eWAYHeader: org.birchavenue.eway.EWAYHeader): Either[scalaxb.Fault[Any], org.birchavenue.eway.QueryCustomerResponse]
  def queryCustomerByReference(value: org.birchavenue.eway.QueryCustomerByReference, eWAYHeader: org.birchavenue.eway.EWAYHeader): Either[scalaxb.Fault[Any], org.birchavenue.eway.QueryCustomerByReferenceResponse]
  def processPayment(value: org.birchavenue.eway.ProcessPayment, eWAYHeader: org.birchavenue.eway.EWAYHeader): Either[scalaxb.Fault[Any], Option[org.birchavenue.eway.CCPaymentResponse]]
  def processPaymentWithBeagle(value: org.birchavenue.eway.ProcessPaymentWithBeagle, eWAYHeader: org.birchavenue.eway.EWAYHeader): Either[scalaxb.Fault[Any], Option[org.birchavenue.eway.CCPaymentResponse]]
  def processPaymentWithCVN(value: org.birchavenue.eway.ProcessPaymentWithCVN, eWAYHeader: org.birchavenue.eway.EWAYHeader): Either[scalaxb.Fault[Any], Option[org.birchavenue.eway.CCPaymentResponse]]
  def queryPayment(value: org.birchavenue.eway.QueryPayment, eWAYHeader: org.birchavenue.eway.EWAYHeader): Either[scalaxb.Fault[Any], org.birchavenue.eway.QueryPaymentResponse]
}




