// Generated by <a href="http://scalaxb.org/">scalaxb</a>.
package org.birchavenue.eway


trait Rapid30Soap {
  def createAccessCode(request: Option[org.birchavenue.eway.CreateAccessCodeRequest]): Either[scalaxb.Fault[Any], org.birchavenue.eway.CreateAccessCodeResponse]
  def getAccessCodeResult(request: Option[org.birchavenue.eway.GetAccessCodeResultRequest]): Either[scalaxb.Fault[Any], org.birchavenue.eway.GetAccessCodeResultResponse]
}




